# Generated by Django 3.1.3 on 2020-11-17 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20201116_2135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('owner', 'event_name', 'start')},
        ),
    ]
