# Generated by Django 3.1.3 on 2020-11-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201116_1504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'address')},
        ),
    ]
